export const themes = {
  light: [
    'base16-light',
    'coy',
    'funky',
    'mdn-like',
    'neo',
    'rose-pine-dawn',
    'solarized_light',
    'yeti',
  ],
  dark: [
    '3024-night',
    'ambiance',
    'base16-dark',
    'cobalt',
    'dark',
    'dracula',
    'dracula-custom',
    'jellybeans',
    'material',
    'mbo',
    'mehdi',
    'midnight',
    'monokai',
    'okaidia',
    'panda-syntax',
    'rose-pine',
    'rose-pine-moon',
    'solarized_dark',
    'tomorrow',
    'twilight',
    'zenburn',
  ],
}
